use pest::Parser;
pub use pest::iterators::Pair;
use pest_derive::Parser;

/// Main parser struct generated by Pest.
#[derive(Parser)]
#[grammar = "grammar.pest"]
pub struct LangParser;

/// Type alias for a parsed grammar rule.
pub type ParsePair<'i> = Pair<'i, Rule>;

/// Utility function to parse the main program structure.
pub fn parse_source(input: &str) -> Result<ParsePair<'_>, Box<pest::error::Error<Rule>>> {
    let mut pairs = LangParser::parse(Rule::program, input)?;
    Ok(pairs.next().unwrap())
}
